### ISSUE TITLE
Faulty plugin on new project

### ISSUE THREAD

**Issue by ShinobiWPS** [callstack/parcel-plugin-linaria#13]
## Environment
files are .js (not .jsx)

## Description

New project with Parcel
installed linaria,
installed plugin,
error.

## Reproducible Demo

https://send.firefox.com/download/602e35e719ad22f9/#eue9cTl9rNs1MolN9Y_x3g

**Comment by jayu** [comment]
I cannot reproduce the issue. The link has expired :/ If it still an issue, please update the repro and maybe share more info about the error you got. I'm closing it for now
